# Generated by Django 5.1 on 2024-09-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestbidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestbidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
